project/tasks/forms.py
# /project/tasks/forms.py


from flask_wtf import Form
from wtforms import TextField, DateField, IntegerField, \
    SelectField
from wtforms.validators import DataRequired


class AddTaskForm(Form):
    task_id = IntegerField('Priority')
    name = TextField('Task Name', validators=[DataRequired()])
    due_date = DateField(
        'Date Due (mm/dd/yyyy)',
        validators=[DataRequired()], format='%m/%d/%Y'
    )
    priority = SelectField(
        'Priority',
        validators=[DataRequired()],
        choices=[
            ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'),
            ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')
        ]
    )
    status = IntegerField('Status')

project/tasks/views.py
# /project/tasks/views.py

from flask import flash, redirect, render_template, request, \
    session, url_for, Blueprint
from forms import AddTaskForm
from project import db
from project.views import login_required
from project.models import Task


################
#### config ####
################

tasks_blueprint = Blueprint(
    'tasks', __name__,
    url_prefix='/tasks',
    template_folder='templates',
    static_folder='static'
)


################
#### routes ####
################

@tasks_blueprint.route('/tasks/')
@login_required
def tasks():
    print session['name']
    open_tasks = db.session.query(Task) \
        .filter_by(status='1').order_by(Task.due_date.asc())
    closed_tasks = db.session.query(Task) \
        .filter_by(status='0').order_by(Task.due_date.asc())
    return render_template(
        'tasks.html',
        form=AddTaskForm(request.form),
        open_tasks=open_tasks,
        closed_tasks=closed_tasks,
        username = session['name']
    )


# Add new tasks:
@tasks_blueprint.route('/add/', methods=['GET', 'POST'])
@login_required
def new_task():
    import datetime
    error = None
    form = AddTaskForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_task = Task(
                form.name.data,
                form.due_date.data,
                form.priority.data,
                datetime.datetime.utcnow(),
                '1',
                session['user_id']
            )
            db.session.add(new_task)
            db.session.commit()
            flash('New entry was successfully posted. Thanks.')
            return redirect(url_for('tasks.tasks'))
        else:
            return render_template('tasks.html', form=form, error=error)


# Mark tasks as complete:
@tasks_blueprint.route('/complete/<int:task_id>/',)
@login_required
def complete(task_id):
    new_id = task_id
    task = db.session.query(Task).filter_by(task_id=new_id)
    if session['user_id'] == task.first().user_id or session['role'] == "admin":
        task.update({"status": "0"})
        db.session.commit()
        flash('The task was marked as complete. Nice.')
        return redirect(url_for('tasks.tasks'))
    else:
        flash('You can only update tasks that belong to you.')
        return redirect(url_for('tasks.tasks'))


# Delete Tasks:
@tasks_blueprint.route('/delete/<int:task_id>/',)
@login_required
def delete_entry(task_id):
    new_id = task_id
    task = db.session.query(Task).filter_by(task_id=new_id)
    if session['user_id'] == task.first().user_id or session['role'] == "admin":
        task.delete()
        db.session.commit()
        flash('The task was deleted. Why not add a new one?')
        return redirect(url_for('tasks.tasks'))
    else:
        flash('You can only delete tasks that belong to you.')
        return redirect(url_for('tasks.tasks'))

project/tasks/templates/tasks.html
<!-- /project/tasks/templates/tasks.html -->


{% extends "template.html" %}

{% block content %}

  <h1>Welcome to FlaskTaskr</h1>
  <div class="add-task">
    <div class="lead">Add a new task:</div>
      <form action="{{ url_for('tasks.new_task') }}" method="post">
        {{ form.csrf_token }}
        <p>
        {{ form.name(placeholder="name") }}
        <span class="error">
          {% if form.name.errors %}
            {% for error in form.name.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        </span>
        </p>
        <p>
        {{ form.due_date(placeholder="due date (mm/dd/yyyy)") }}
        <span class="error">
          {% if form.due_date.errors %}
            {% for error in form.due_date.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        </span>
        </p>
        <p>
        {{ form.priority.label }}
        {{ form.priority(class="form-control",style="max-width:60px;") }}
        <span class="error">
          {% if form.priority.errors %}
            {% for error in form.priority.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        </span>
        </p>
        <br>
        <p><button class="btn btn-sm btn-success" type="submit">Submit</button></p>
      </form>
  </div>
<div class="entries">
  <br>
  <br>
  <div class="lead">Open tasks</div>
  <br>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Task Name</th>
        <th>Due Date</th>
        <th>Posted Date</th>
        <th>Priority</th>
        <th>Posted By</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    {% for ot in open_tasks %}
      <tr>
        <td>{{ ot.name }}</td>
        <td>{{ ot.due_date }}</td>
        <td>{{ ot.posted_date }}</td>
        <td>{{ ot.priority }}</td>
        <td>{{ ot.poster.name }}</td>
        <td>
          {% if ot.poster.name == session.name or session.role == "admin" %}
            <a href="{{ url_for('tasks.delete_entry', task_id = ot.task_id) }}">Delete</a>  -
            <a href="{{ url_for('tasks.complete', task_id = ot.task_id) }}">Mark as Complete</a>
          {% else %}
            <span>N/A</span>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
<br>
<br>
<div class="entries">
  <div class="lead">Closed tasks</div>
  <br>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Task Name</th>
        <th>Due Date</th>
        <th>Posted Date</th>
        <th>Priority</th>
        <th>Posted By</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    {% for ct in closed_tasks %}
      <tr>
        <td>{{ ct.name }}</td>
        <td>{{ ct.due_date }}</td>
        <td>{{ ct.posted_date }}</td>
        <td>{{ ct.priority }}</td>
        <td>{{ ct.poster.name }}</td>
        <td>
          {% if ct.poster.name == session.name or session.role == "admin" %}
            <a href="{{ url_for('tasks.delete_entry', task_id = ct.task_id) }}">Delete</a>
          {% else %}
            <span>N/A</span>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    <tbody>
  </table>
</div>

{% endblock %}